logging:
  level:
    root: WARN

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: OFF
    # set 'TRACE' to log as well SQL parameters
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    # JpaTransactionManager is filtered in TxSqlNoiseFilter class to show only 'open transaction', 'rollback' or 'commit' statements